import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'First Steps',
      items: [
        'first-steps/how-sealmetrics-works',
        'first-steps/how-superprivacy-tracking-works',
        'first-steps/cookieless-tracking',
        'first-steps/first-party-tracker',
        'first-steps/quick-journey-through-the-platform',
        'first-steps/setting-up-trackers-in-sealmetrics',
        'first-steps/how-to-measure-conversions-and-micro-conversions',
        'first-steps/google-tag-manager-vs-direct-code',
        'first-steps/sealmetrics-kick-off-video',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/dashboard',
        'features/acquisition-report',
        'features/roas-evolution-report',
        'features/funnel-report',
        'features/how-to-add-domains-in-your-account',
        'features/how-to-setup-cost-calculator',
        'features/definitions',
        'features/how-to-add-vat-number-in-my-invoices',
        'features/cost-calculator',
        'features/1st-party-tracker',
        'features/enhance-your-sealmetrics-with-ip-access-control',
        'features/understanding-event-properties-in-sealmetrics',
      ],
    },
    {
      type: 'category',
      label: 'Platform',
      items: [
        'platform/update-billing-info',
        'platform/how-do-i-create-an-admin-user',
        'platform/how-to-change-your-time-zone',
        'platform/step-by-step-guide-how-to-change-your-password',
        'platform/billing-screen-information',
        'platform/how-to-add-a-new-user',
        'platform/how-to-add-a-new-account',
        'platform/how-to-cancel-your-subscription',
        'platform/find-sealmetrics-id-account',
        'platform/understanding-the-difference-between-global-tracker-and-superprivacy-tracker',
        'platform/how-to-share-your-affiliate-link',
        'platform/using-the-sealmetrics-api-basics-reports-and-kpis',
        'platform/bypass-pos-or-referrer',
        'platform/roles-management',
        'platform/access-restricted-to-authorized-ips',
        'platform/bot-traffic-filtering-in-sealmetrics',
        'platform/using-subdomain-differentiation-in-url-analytics',
        'platform/accessing-real-time-data',
        'platform/how-to-obtain-your-api-token-from-the-sealmetrics-platform',
        'platform/how-to-avoid-conversions-being-attributed-to-payment-in-sealmetrics',
        'platform/how-to-delete-an-account',
        'platform/how-sealmetrics-consolidates-data',
        'platform/what-is-gtm-msrappspotcom',
        'platform/understanding-content-grouping-in-sealmetrics',
      ],
    },
    {
      type: 'category',
      label: 'Metric Insights',
      items: [
        'metric-insights/how-does-sealmetrics-calculate-entrances',
        'metric-insights/how-to-change-utm-parameters',
        'metric-insights/how-to-track-social-ads-campaigns',
        'metric-insights/how-to-track-google-ads-campaigns',
        'metric-insights/how-to-track-react-sites',
        'metric-insights/how-to-track-spa-sites',
        'metric-insights/how-to-track-ajax-forms',
        'metric-insights/understanding-the-not-set-value-in-your-reports',
        'metric-insights/why-does-ga4-measure-more-than-sealmetrics',
        'metric-insights/definitions',
        'metric-insights/what-is-rejoined-traffic',
        'metric-insights/update-to-the-sealmetrics-pixel',
        'metric-insights/how-sealmetrics-tracks-traffic-without-cookies',
        'metric-insights/understanding-referrer-loss-and-direct-traffic-in-sealmetrics',
        'metric-insights/how-sealmetrics-calculates-seo-traffic',
        'metric-insights/what-is-a-term-in-sealmetrics',
        'metric-insights/how-sealmetrics-differentiates-referrer-traffic-from-direct-traffic',
        'metric-insights/what-attribution-model-does-sealmetrics-use',
        'metric-insights/why-do-i-see-more-conversions-or-revenue-in-sealmetrics-than-in-my-erp',
        'metric-insights/what-is-gtm-msrappspotcom-and-how-to-prevent-it-from-triggering-tags-in-gtm',
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [
        'legal/frequently-asked-legal-questions',
        'legal/is-sealmetrics-gdpr-eprivacy-regulation-ccpa-pecr-compliant',
        'legal/can-i-exclude-internal-ips',
        'legal/how-sealmetrics-blocks-bot-traffic-without-handling-ips',
        'legal/why-we-cant-filter-internal-traffic-at-sealmetrics',
        'legal/sealmetrics-undergoes-comprehensive-audit-by-complyorg-for-enhanced-transparency-and-compliance',
        'legal/what-metrics-we-collect',
      ],
    },
    {
      type: 'category',
      label: 'Company',
      items: [
        'company/customer-support-at-sealmetrics-here-for-you',
        'company/the-2-clear-steps-we-always-follow-at-sealmetrics-before-developing-a-report-kpi-or-feature',
        'company/public-access-to-server-statistics',
        'company/sealmetrics-philosophy',
      ],
    },
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        'api-documentation/introduction-sealmetrics-api',
        'api-documentation/authentication',
        'api-documentation/api-endpoints',
        'api-documentation/login-endpoint',
        'api-documentation/acquisition-endpoint',
        'api-documentation/account-endpoints',
        'api-documentation/pages-endpoint',
        'api-documentation/conversions-endpoint',
        'api-documentation/microconversions-endpoint',
        'api-documentation/roas-evolution-endpoint',
        'api-documentation/funnel-endpoint',
        'api-documentation/set-click-endpoint',
        'api-documentation/appendix',
        'api-documentation/troubleshooting',
        'api-documentation/implementation-guides',
      ],
    },
  ],
};

export default sidebars;